//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long ID { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<double> max_limit { get; set; }
    }
}
